---
- name: Install python3, docker, docker-compose
  hosts: aws_ec2
  become: yes
  gather_facts: False
  tasks:
    - name: Ensure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Ensure docker compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-{{lookup('pipe', 'uname -s')}}-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is started
      systemd:
        name: docker
        state: started
    - name: Ensure docker python module is installed
      pip:
        name:
          - docker
          - docker-compose

- name: Add user to docker group
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Ensure user is added to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Start container
  hosts: aws_ec2
  become: yes
  become_user: ec2-user
  tasks:
    - name: Ensure container is runnind
      docker_container:
        name: sample-nodejs-app-1
        state: started
        image: "246167819468.dkr.ecr.us-east-1.amazonaws.com/sample-nodejs-app-1:4.0"
        pull: true
        ports:
          - "3000:3000"
